### ISSUE TITLE
Windows comilation process doesn't work

### ISSUE THREAD

**Issue by pianonyy** [ncblair/NeuralGranulator#3]
Hello! I am trying to reproduce your great work, but facing some issues win10 :
![image](https://user-images.githubusercontent.com/48867176/143620648-6738d911-da06-433a-a25d-71eded3463f5.png)
How can I solve it?

**Comment by pianonyy** [comment]
I understand, that the problem was with non installed packages libtorch and Juce. But how to cope with it? 
![image](https://user-images.githubusercontent.com/48867176/143622844-43d1a9e2-31f6-4b18-86dd-1583c00590bc.png)

**Comment by ncblair** [comment]
Hi! the codebase really shouldn't be public at this point. It's unfinished, constantly changing, and not really reproduce-able at this point (check back in a couple weeks). That being said, If you want to reproduce the code you are going to have to download libtorch and JUCE and put those folders in your working directory. You would also need to train a model with the python code and put that in the correct directory for the c++ to load it.
